arguments <- commandArgs(trailingOnly = TRUE)
if (length(arguments) != 1L) stop("Usage: Rscript --vanilla scripts/predict.R config/report.R")
script_file <- sub("^--file=", "", commandArgs()[grepl("^--file=", commandArgs())][1])
project_root <- normalizePath(file.path(dirname(script_file), ".."), winslash = "/", mustWork = TRUE)
for (module in c("data", "features", "preprocessing", "svr", "submission")) {
  source(file.path(project_root, "R", paste0(module, ".R")))
}
config <- load_analysis_config(arguments[1], project_root)
metadata <- read_training_metadata(input_path(config, config$train_metadata))
training_features <- align_features(read_features(input_path(config, config$train_features, config$feature_root)), metadata$image_path)
test_metadata <- read_test_metadata(input_path(config, config$test_metadata))
test_images <- unique(test_metadata$image_path)
test_features <- align_features(read_features(input_path(config, config$test_features, config$feature_root)), test_images)
model <- fit_biomass_model(training_features, metadata, config$parameters, config$components)
predictions <- data.frame(image_path = test_images, predict_biomass_model(model, test_features), check.names = FALSE)
sample_submission <- utils::read.csv(input_path(config, config$sample_submission), stringsAsFactors = FALSE)
submission <- make_submission(predictions, test_metadata, sample_submission)
output_dir <- output_directory(config, "prediction")
saveRDS(model, file.path(output_dir, "pca_svr.rds"))
utils::write.csv(predictions, file.path(output_dir, "image_predictions.csv"), row.names = FALSE)
utils::write.csv(submission, file.path(output_dir, "submission.csv"), row.names = FALSE)
